fruts = ['banana', 'apple', 'pear', 'banana', 'kiwi', 'orange', 'banana', 'pear']
print(fruts.count("apple"))
print(fruts.count("tangerine"))
print(fruts.index('banana'))
print(fruts.index('banana', 4))
fruts.reverse()
print(fruts)
fruts.append('grape')
print(fruts)
fruts.sort()
print(fruts)
print(fruts.pop())